name: Manual Build and Release cloudflared (ARMv6)

on:
  workflow_dispatch:
    inputs:
      cloudflared_tag:
        description: 'Tag of cloudflared to build (e.g., 2024.5.0)'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    name: Cross-build cloudflared for ARMv6 with static OpenSSL

    steps:
      - name: Checkout this repository (workflow host repo)
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache: true

      - name: Install build dependencies
        run: |
          sudo dpkg --add-architecture armhf
          sudo apt-get update
          sudo apt-get install -y \
            gcc-arm-linux-gnueabihf \
            libc6-dev-armhf-cross \
            pkg-config \
            make \
            perl \
            wget \
            git

      - name: Clone cloudflared
        run: |
          git clone https://github.com/cloudflare/cloudflared.git
          cd cloudflared
          git checkout ${{ github.event.inputs.cloudflared_tag }}

      - name: Build static OpenSSL for ARMv6
        run: |
          OPENSSL_VERSION=3.2.1
          wget https://www.openssl.org/source/openssl-$OPENSSL_VERSION.tar.gz
          tar -xzf openssl-$OPENSSL_VERSION.tar.gz
          cd openssl-$OPENSSL_VERSION
          ./Configure linux-armv4 no-shared no-dso --prefix=$PWD/../openssl-armv6 --cross-compile-prefix=arm-linux-gnueabihf-
          make -j$(nproc)
          make install_sw
          cd ..

      - name: Build cloudflared with static OpenSSL
        working-directory: ./cloudflared
        env:
          GOOS: linux
          GOARCH: arm
          GOARM: 6
          CC: arm-linux-gnueabihf-gcc
          CGO_ENABLED: 1
          CGO_CFLAGS: "-I$GITHUB_WORKSPACE/openssl-armv6/include"
          CGO_LDFLAGS: "-L$GITHUB_WORKSPACE/openssl-armv6/lib -static"
        run: |
          go build -v -o cloudflared-armv6

      - name: Archive binary
        working-directory: ./cloudflared
        run: |
          tar -czvf cloudflared-armv6-${{ github.event.inputs.cloudflared_tag }}.tar.gz cloudflared-armv6

      - name: Upload to GitHub Releases
        uses: softprops/action-gh-release@v2
        with:
          name: "cloudflared ARMv6 ${{ github.event.inputs.cloudflared_tag }}"
          tag_name: "cloudflared-${{ github.event.inputs.cloudflared_tag }}"
          files: cloudflared/cloudflared-armv6-${{ github.event.inputs.cloudflared_tag }}.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
