name: Manual Build and Release cloudflared (ARMv6)

on:
  workflow_dispatch:
    inputs:
      cloudflared_tag:
        description: "Tag of cloudflared to build (e.g., 2024.5.0)"
        required: true
        type: string

jobs:
  build:
    name: Cross-build cloudflared for ARMv6 with static OpenSSL
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this repository
        uses: actions/checkout@v4

      - name: Clone cloudflared
        run: |
          git clone https://github.com/cloudflare/cloudflared.git
          cd cloudflared
          git checkout ${{ github.event.inputs.cloudflared_tag }}

      - name: Cross-build on ARMv6 using run-on-arch-action
        uses: uraimo/run-on-arch-action@v3
        with:
          arch: armv6
          distro: bookworm
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          install: |
            apt-get update
            apt-get install -y \
              gcc \
              pkg-config \
              make \
              perl \
              wget \
              git \
              golang
          run: |
            set -eux

            # Set up Go env manually
            export PATH="/usr/lib/go-1.18/bin:$PATH"

            # Build OpenSSL for ARMv6
            OPENSSL_VERSION=3.2.1
            wget https://www.openssl.org/source/openssl-$OPENSSL_VERSION.tar.gz
            tar -xzf openssl-$OPENSSL_VERSION.tar.gz
            cd openssl-$OPENSSL_VERSION
            ./Configure linux-armv4 no-shared no-dso --prefix=$PWD/../openssl-armv6
            make -j$(nproc)
            make install_sw
            cd ..

            # Build cloudflared
            cd cloudflared
            export CGO_ENABLED=1
            export GOOS=linux
            export GOARCH=arm
            export GOARM=6
            export CGO_CFLAGS="-I$(realpath ../openssl-armv6/include)"
            export CGO_LDFLAGS="-L$(realpath ../openssl-armv6/lib) -static"
            go build -v -o cloudflared-armv6

            tar -czvf cloudflared-armv6-${{ github.event.inputs.cloudflared_tag }}.tar.gz cloudflared-armv6
            mv cloudflared-armv6-${{ github.event.inputs.cloudflared_tag }}.tar.gz /tmp/

      - name: Upload to GitHub Releases
        uses: softprops/action-gh-release@v2
        with:
          name: "cloudflared ARMv6 ${{ github.event.inputs.cloudflared_tag }}"
          tag_name: "cloudflared-${{ github.event.inputs.cloudflared_tag }}"
          files: /tmp/cloudflared-armv6-${{ github.event.inputs.cloudflared_tag }}.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.TAP_TOKEN }}
